#exampleSubmit.sub
universe = vanilla
log = example_$(Cluster).log
executable = example.sh
arguments = $(Process)
output = example_$(Cluster)_$(Process).out
error = example_$(Cluster)_$(Process).err

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files =http://proxy.chtc.wisc.edu/SQUID/chtc/python39.tar.gz, packages.tar.gz, example.sh

Requirements = (Target.HasCHTCStaging == true)

request_cpus = 4
request_memory = 16GB
request_disk = 16GB

queue 1

